#!/usr/bin/env python3
"""Build compact on-the-fly GT metadata caches from merged BIN/CSV data."""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

from .config import SATSConfig, filter_trial_ids
from .dataset_on_the_fly import (
    _all_trial_ids_from_index_or_raw,
    meta_cache_path,
    meta_cache_signature,
    save_trial_meta_cache,
)

log = logging.getLogger(__name__)


def _select_trial_ids_for_cache(cfg: SATSConfig, trial_ids: list[str]) -> list[str]:
    """Apply cache-build trial filters in the same order as training."""

    return filter_trial_ids(
        trial_ids,
        include_materials=cfg.include_materials,
        exclude_diameters=cfg.exclude_diameters,
    )


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Build compact SATS GPU/on-the-fly GT meta caches",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--raw-dir", default="learning_data/sensor_raw_bin",
                   help="merged BIN/CSV root generated by prepare_learning_data.py")
    p.add_argument("--out-dir", default="learning_data/gt_meta_cache",
                   help="compact meta cache output directory")
    p.add_argument("--dataset-index-path", default="learning_data/gt/dataset_index.json")
    p.add_argument("--trial-ids", nargs="+", default=[],
                   help="specific trial ids. Empty means discover all trials")
    p.add_argument("--include-materials", nargs="+", default=[],
                   help="material keys to include, e.g. eco20_xy1 eco50_xy1")
    p.add_argument("--exclude-diameters", nargs="+", type=int, default=[])
    p.add_argument("--overwrite", action="store_true")
    p.add_argument("--grid-step-mm", type=float, default=0.5,
                   help="GT/output grid spacing used by the target training run")
    p.add_argument("--grid-size", type=int, default=0,
                   help="0 means infer from [-10,10] and grid-step-mm")
    p.add_argument("--seq-len", type=int, default=1000)
    p.add_argument("--window-size", type=int, default=10)
    p.add_argument("--z-balance-bin-width-mm", type=float, default=0.005)
    p.add_argument("--plateau-stride", type=int, default=10)
    p.add_argument("--loading-stride", type=int, default=1)
    p.add_argument("--saturation-stride", type=int, default=2)
    p.add_argument("--prefer-merged-bin", action=argparse.BooleanOptionalAction, default=True)
    return p


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%H:%M:%S",
    )
    args = _build_parser().parse_args()
    grid_size = args.grid_size
    if grid_size <= 0:
        grid_size = int(round(20.0 / args.grid_step_mm)) + 1

    cfg = SATSConfig(
        raw_dir=args.raw_dir,
        dataset_index_path=args.dataset_index_path,
        gt_meta_cache_dir=args.out_dir,
        include_materials=args.include_materials,
        exclude_diameters=args.exclude_diameters,
        grid_step_mm=args.grid_step_mm,
        grid_size=grid_size,
        seq_len=args.seq_len,
        window_size=args.window_size,
        z_balance_bin_width_mm=args.z_balance_bin_width_mm,
        plateau_stride=args.plateau_stride,
        loading_stride=args.loading_stride,
        saturation_stride=args.saturation_stride,
        prefer_merged_bin=args.prefer_merged_bin,
    )

    trial_ids = args.trial_ids or _all_trial_ids_from_index_or_raw(cfg)
    trial_ids = _select_trial_ids_for_cache(cfg, trial_ids)

    out_dir = Path(cfg.gt_meta_cache_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    manifest = {
        "format": "sats_on_the_fly_meta_cache_manifest_v1",
        "raw_dir": str(Path(cfg.raw_dir)),
        "include_materials": cfg.include_materials,
        "exclude_diameters": cfg.exclude_diameters,
        "signature": meta_cache_signature(cfg),
        "trials": [],
    }

    log.info("meta cache build start: trials=%d out=%s", len(trial_ids), out_dir)
    for trial_id in trial_ids:
        path = save_trial_meta_cache(trial_id, cfg, overwrite=args.overwrite)
        manifest["trials"].append(
            {
                "trial_id": trial_id,
                "path": str(meta_cache_path(cfg, trial_id)),
                "created": path is not None and Path(path).exists(),
            }
        )

    manifest_path = out_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    log.info("meta cache manifest 저장: %s", manifest_path)


if __name__ == "__main__":
    main()
